package com.justen.auth.core.enums;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_BLOCKED,
    MFA_CHALLENGE_ISSUED,
    MFA_SUCCESS,
    MFA_FAILURE,
    MFA_ENABLED,
    MFA_DISABLED,
    RECOVERY_CODE_USED,
    TOKEN_ISSUED,
    TOKEN_REFRESH,
    TOKEN_REUSE_DETECTED,
    TOKEN_REVOKED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    EXTERNAL_ACCOUNT_LINKED,
    EXTERNAL_ACCOUNT_UNLINKED
}
